
server:
  port: 16666
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        #后台
        - uri: lb://web-back
          predicates:
            - Path=/back/**
          filters:
            - StripPrefix=1
        #搜索
        - uri: lb://web-search
          predicates:
            - Path=/search/**
        #详情
        - uri: lb://web-item
          predicates:
            - Path=/item/**,/html/**
        #sso
        - uri: lb://web-sso
          predicates:
            - Path=/sso/**
        #购物车
        - uri: lb://web-cart
          predicates:
            - Path=/cart/**
        #订单
        - uri: lb://web-order
          predicates:
            - Path=/order/**
        #添加收货地址
        - uri: lb://web-order
          predicates:
            - Path=/address/**
        #付费
        - uri: lb://web-order
          predicates:
            - Path=/pay/**
        #前台
        - uri: lb://web-front
          predicates:
            - Path=/**